name: Lint Python (PR changed files)

on:
  pull_request:
    paths:
      - 'backend/backend-python/**/*.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout (full history for reliable diffs)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch PR base ref
        shell: bash
        run: |
          # Ensure both base and head exist locally (robust for forks)
          git fetch --no-tags --prune --depth=1 origin "${{ github.event.pull_request.base.ref }}":pr_base || true
          git fetch --no-tags --prune --depth=1 origin "pull/${{ github.event.pull_request.number }}/head":pr_head || true

      - name: Install uv (provides uvx)
        run: pipx install uv

      - name: Sync backend-python dependencies
        run: |
          uv --project backend/backend-python sync

      - name: Run linting on changed files
        shell: bash
        run: |
          # Compute base and head refs
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          BASE_REF=$(git rev-parse --verify pr_base 2>/dev/null || echo "$BASE_SHA")
          HEAD_REF=$(git rev-parse --verify pr_head 2>/dev/null || echo "$HEAD_SHA")

          # Run the centralized linting script for pylint_v1 workflow
          ./tests/run_pylint_v1.sh "$BASE_REF" "$HEAD_REF"
